package de.oth.othappserver.exceptions;

import java.lang.System;

@kotlin.Metadata(mv = {1, 4, 1}, bv = {1, 0, 3}, k = 1, d1 = {"\u0000\u0014\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\u0018\u0000 \u00052\u00020\u0001:\u0001\u0005B\u0005\u00a2\u0006\u0002\u0010\u0002J\n\u0010\u0003\u001a\u0004\u0018\u00010\u0004H\u0016\u00a8\u0006\u0006"}, d2 = {"Lde/oth/othappserver/exceptions/InvalidSyncTokenProblem;", "Lorg/zalando/problem/AbstractThrowableProblem;", "()V", "getCause", "Lorg/zalando/problem/Exceptional;", "Companion", "oth-app-server"})
public final class InvalidSyncTokenProblem extends org.zalando.problem.AbstractThrowableProblem {
    @org.jetbrains.annotations.NotNull()
    private static final java.net.URI TYPE = null;
    @org.jetbrains.annotations.NotNull()
    public static final de.oth.othappserver.exceptions.InvalidSyncTokenProblem.Companion Companion = null;
    
    @org.jetbrains.annotations.Nullable()
    @java.lang.Override()
    public org.zalando.problem.Exceptional getCause() {
        return null;
    }
    
    public InvalidSyncTokenProblem() {
        super();
    }
    
    @kotlin.Metadata(mv = {1, 4, 1}, bv = {1, 0, 3}, k = 1, d1 = {"\u0000\u0014\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\b\u0086\u0003\u0018\u00002\u00020\u0001B\u0007\b\u0002\u00a2\u0006\u0002\u0010\u0002R\u0011\u0010\u0003\u001a\u00020\u0004\u00a2\u0006\b\n\u0000\u001a\u0004\b\u0005\u0010\u0006\u00a8\u0006\u0007"}, d2 = {"Lde/oth/othappserver/exceptions/InvalidSyncTokenProblem$Companion;", "", "()V", "TYPE", "Ljava/net/URI;", "getTYPE", "()Ljava/net/URI;", "oth-app-server"})
    public static final class Companion {
        
        @org.jetbrains.annotations.NotNull()
        public final java.net.URI getTYPE() {
            return null;
        }
        
        private Companion() {
            super();
        }
    }
}